import type { Metadata } from "next";
import "../globals.css";
import { LayoutProvider } from "@/providers/layout-provider";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const AuthLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <LayoutProvider>{children}</LayoutProvider>
  );
}

export default AuthLayout;