import type { Metadata } from "next";

import { LayoutProvider } from "@/providers/layout-provider";
import AuthProvider from "@/contexts/auth.context";

export const metadata: Metadata = {
  title: "TutorDem",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <LayoutProvider>{children}</LayoutProvider>
    </AuthProvider>
  );
}
